### ISSUE TITLE
AJAX submit

### ISSUE THREAD

**Issue by pvernaglia** [mgildea/Multi-Step-Form-Js#23]
Hi, I'm trying to submit a form with ajax after validation, I've tried doing this:

$(".msf:first").multiStepForm({
	        activeIndex : 0,
	        allowClickNavigation : true,    
	        allowUnvalidatedStep : false,    
	        hideBackButton : false,
	        validate : {
		        submitHandler: function(form) {
				    jQuery.ajax({
			            url: form.action,
			            data: $(form).serialize(),
			            type: form.method,
			            success: function(response) {
			                $('.results').replaceWith(response);
			            }
			        });
					return false;
					} 
	        }    
	    });

But it doesn't appear that submitHandler is doing anything.  Is this correct way to implement this or does anyone have an example how to use this with ajax calls. thanks

**Comment by lvmajor** [comment]
@pvernaglia please try to format the code so it's more easily readable if you want people to try and help you out :)

You can surround the code with triple backticks and it will format it in a pretty code block (also you can specify the language for colorization).

```javascript
$(".msf:first").multiStepForm({
  activeIndex: 0,
  allowClickNavigation: true,
  allowUnvalidatedStep: false,
  hideBackButton: false,
  validate: {
    submitHandler: function (form) {
      jQuery.ajax({
        url: form.action,
        data: $(form).serialize(),
        type: form.method,
        success: function (response) {
          $('.results').replaceWith(response);
        }
      });
      return false;
    }
  }
});
```

As for the submitHandler, I tried finding where the problem was and found out that the actual version of this library does not seem to use this setting anymore. It was removed [here](https://github.com/mgildea/Multi-Step-Form-Js/commit/1c4b45cc3b1a0ae6d72dc2512098d1b0ece47b13#diff-ec7c560a118dd6f65fdbe5064766b5daR309) where a function was created to avoid code duplication and validate specific views. 

As to why it was removed, I can't tell for sure at the moment, maybe @mgildea could lighten us up on this one :)
